### ISSUE TITLE
Missing matrix inverse at Abstandsklassifikatoren

### ISSUE THREAD

**Issue by thomasbbrunner** [latex4ei/Mensch-Maschine-Kommunikation-1#2]
In section 5.2 (Abstandsklassifikatoren) there is a matrix inverse operation missing when calculating the mahalanobis distance

According to the lecture slides, the weight matrix has to be inverted (chapter 3, slide 9), as the mahalanobis distance is the inverse of the covariance matrix.

**Comment by thomasbbrunner** [comment]
Created PR #3

**Comment by markuspi** [comment]
Resolved by #3
